app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 900000 # 15 min
  access-type: jpa
  update-frequency: 10

  rate_limit: 3
  time_duration: 1
  nano_in_seconds: 1_000_000_000

  retry:
    status-codes: 500, 502, 503, 504
    enable: true
    policy: exponential

    linear:
      attempts: 5
      initial-backoff: 1s
      max-backoff: 10s

    constant:
      attempts: 3
      backoff: 5s

    exponential:
      attempts: 3
      initial-backoff: 1s
      max-backoff: 20s
      jitter: 0.5

  kafka:
    consumer:
      bootstrap-servers: localhost:29091,localhost:29092,localhost:29093
      group-id: scrapper-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      bootstrap-servers: localhost:29091,localhost:29092,localhost:29093
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      linger-ms: 10
      retries: 3
      max-in-flight-requests-per-connection: 1
      enable-idempotence: true

    topic:
      name: link-updates

spring:
  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: scrapper

server:
  port: 8080

logging:
  level:
    root: INFO
    edu.java.scheduler: DEBUG
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
