app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10000
  access-type: jpa
  update-frequency: 10

  retry:
    enable: true
    policy: exponential
    status-codes: [ 500, 502, 503, 504 ]

    linear:
      attempts: 5
      initial-backoff: 1s
      max-backoff: 10s

    constant:
      attempts: 3
      backoff: 5s

    exponential:
      attempts: 3
      initial-backoff: 1s
      max-backoff: 20s
      jitter: 0.5

spring:
  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: scrapper

server:
  port: 8080

logging:
  level:
    root: INFO
    edu.java.scheduler: DEBUG
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
