app:
  telegram-token: ${TELEGRAM-TOKEN}

  retry:
    status-codes: 500, 502, 503, 504
    enable: true
    policy: exponential

    linear:
      attempts: 5
      initial-backoff: 1s
      max-backoff: 10s

    constant:
      attempts: 3
      backoff: 5s

    exponential:
      attempts: 3
      initial-backoff: 1s
      max-backoff: 20s
      jitter: 0.5


spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
