/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq_generated;

import edu.java.scrapper.domain.jooq_generated.tables.Chats;
import edu.java.scrapper.domain.jooq_generated.tables.Links;
import edu.java.scrapper.domain.jooq_generated.tables.LinksToChats;
import javax.annotation.processing.Generated;

/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>CHATS</code>.
     */
    public static final Chats CHATS = Chats.CHATS;

    /**
     * The table <code>LINKS</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>LINKS_TO_CHATS</code>.
     */
    public static final LinksToChats LINKS_TO_CHATS = LinksToChats.LINKS_TO_CHATS;
}
