/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq_generated.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Chats implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer chatId;
    private OffsetDateTime registeredAt;

    public Chats() {
    }

    public Chats(Chats value) {
        this.chatId = value.chatId;
        this.registeredAt = value.registeredAt;
    }

    @ConstructorProperties({"chatId", "registeredAt"})
    public Chats(
        @NotNull Integer chatId,
        @NotNull OffsetDateTime registeredAt
    ) {
        this.chatId = chatId;
        this.registeredAt = registeredAt;
    }

    /**
     * Getter for <code>CHATS.CHAT_ID</code>.
     */
    @NotNull
    public Integer getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>CHATS.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Integer chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>CHATS.REGISTERED_AT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public OffsetDateTime getRegisteredAt() {
        return this.registeredAt;
    }

    /**
     * Setter for <code>CHATS.REGISTERED_AT</code>.
     */
    public void setRegisteredAt(@NotNull OffsetDateTime registeredAt) {
        this.registeredAt = registeredAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Chats other = (Chats) obj;
        if (this.chatId == null) {
            if (other.chatId != null) {
                return false;
            }
        } else if (!this.chatId.equals(other.chatId)) {
            return false;
        }
        if (this.registeredAt == null) {
            if (other.registeredAt != null) {
                return false;
            }
        } else if (!this.registeredAt.equals(other.registeredAt)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        result = prime * result + ((this.registeredAt == null) ? 0 : this.registeredAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Chats (");

        sb.append(chatId);
        sb.append(", ").append(registeredAt);

        sb.append(")");
        return sb.toString();
    }
}
